apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: redis
spec:
  chart:
    name: redis
    chartVersion: 12.8.0
  helmVersion: v3
  values:
    password: repl{{ ConfigOption "password" }}
    master:
      persistence:
        size: repl{{ ConfigOption "psize" }}
    slave:
      persistence:
        size: repl{{ ConfigOption "ssize" }}
