apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: redis
spec:
  collectors:
    - redis:
        collectorName: redis
        uri: redis://admin:{{repl ConfigOption "password"}}@redis-master:6379
